### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by ldes89150** [senkolab/pll-evalboard-synthesizer#2]
https://github.com/senkolab/pll-evalboard-synthesizer/blob/72fe8baceaf71e22345a738f1e8b7c18a5f701ad/src/adf4355_2.py#L204

@rwradema 

Is the s here typos? I guess they should be self

**Comment by rwradema** [comment]
There's a missing line from the original file
   s = self

This was to keep the format convention f(self, arg1, arg2), while making 
a shortcut in code
